apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-postgresql-db
  namespace: {{ .Values.namespace }}
  labels:
    app: petclinic-db
spec:
  selector:
    matchLabels:
      app: petclinic-db
  template:
    metadata:
      labels:
        app: petclinic-db
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: petclinic-postgresql-pvc
      containers:
        - image: postgres:17
          name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: database
          ports:
            - containerPort: 5432
              name: postgresql
          livenessProbe:
            tcpSocket:
              port: postgresql
          readinessProbe:
            tcpSocket:
              port: postgresql
          startupProbe:
            tcpSocket:
              port: postgresql
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
