apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: petclinic-db
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | default "petclinic" | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | default "petclinic" | b64enc | quote }}
  database: {{ .Values.postgresql.auth.database | default "petclinic" | b64enc | quote }}
