apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: petclinic
  labels:
    app: petclinic-db
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username }}
  password: {{ .Values.postgresql.auth.password }}
  database: {{ .Values.postgresql.auth.database }}
