apiVersion: v1
kind: Service
metadata:
  name: petclinic-postgresql-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: petclinic-db
spec:
  selector:
    app: petclinic-db
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}
  type: ClusterIP
