apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: workload
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVICE_BINDING_ROOT
              value: /bindings
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
            - name: POSTGRES_USER
              value: {{ .Values.global.postgresql.auth.username }}
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.global.postgresql.auth.database }}
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: POSTGRES_PORT
              value: "{{ .Values.global.postgresql.port }}"
            - name: POSTGRES_HOST
              value: petclinic-postgresql.default.svc.cluster.local
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
