apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-web
  namespace: petclinic
spec:
  podSelector:
    matchLabels:
      app: petclinic-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: petclinic-app
