apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-petclinic-app
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: petclinic-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: petclinic-app
