apiVersion: v2
name: petclinic-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami
  - name: prometheus
    version: 26.0.0
    repository: https://prometheus-community.github.io/helm-charts
