image:
  repository: ahmedbenrouha01/petclinic
  tag: 3.4.26-SNAPSHOT
  pullPolicy: Always

namespace: petclinic

progressDeadline: 600

service:
  port: 80
  targetPort: 8080


hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  cpuTarget: 70
  memoryTarget: 75

postgresql:
  auth:
    username: petclinic
    password: petclinic
    database: petclinic
  port: 5432

prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    service:
      type: ClusterIP
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

  extraScrapeConfigs: |
    - job_name: 'petclinic'
      scrape_interval: 30s
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: ['petclinic-svc.petclinic.svc.cluster.local']

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 32000
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://petclinic-prometheus-server.default.svc.cluster.local:80
          access: proxy
          isDefault: true


  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - grafana.local
    pathType: Prefix
    paths:
      - /
