apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: petclinic-chart
    repoURL: https://github.com/AhmedBenRouha01/petClinic-DevOps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
