name: Java CI with Maven and Docker image build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven and Run Tests
        run: ./mvnw package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: List Target Directory
        run: ls

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract Version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ahmedbenrouha01/petclinic:latest -t ahmedbenrouha01/petclinic:${{ env.version }} -f .devcontainer/Dockerfile .

      - name: Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ahmedbenrouha01/petclinic:latest
          docker push ahmedbenrouha01/petclinic:${{ env.version }}

      - name: Update Helm Values
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s/tag:.*/tag: ${{ env.version }}/" petclinic-chart/values.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add petclinic-chart/values.yaml
          git commit -m "Update image tag to ${{ env.version }}"
          git push

      
